version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands: 
      - java -version
      - mvn -version
      - echo Build started on `date`
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/function.zip
  discard-paths: yes
